# Generated by Buildr 1.4.20, change to your liking
# Standard maven2 repository
repositories.remote << 'http://repo1.maven.org/maven2'

desc '["jTtt"]'
define 'jTtt' do
  project.group = '["com.danielirvine.jttt"]'
  project.version = '["1.0-SNAPSHOT"]'
  package :jar, :id => 'jTtt'
  compile.options.target = '1.8'
  compile.options.source = '1.8'
end
