require 'lock_jar/buildr'

def jetty_jars(*jars)
  jars.map { |j| "org.eclipse.jetty:#{j}:jar:9.2.3.v20140905"}
end

CORE = Dir['../cli/**/*.jar']
SPRING = 'org.springframework:spring-webmvc:jar:4.1.0.RELEASE'
JETTY = jetty_jars('jetty-security', 'jetty-jsp', 'jetty-webapp', 'jetty-servlet', 'jetty-server', 'jetty-util')
SERVLET_API = 'javax.servlet:javax.servlet-api:jar:3.1.0'


ALL = [CORE, SPRING, JETTY, SERVLET_API].flatten

lock_jar do

  ALL.each do |j|
    str = j.to_s

    if str.include?(":")
      jar str
    else
      local str
    end
  end

end

coffee_files = FileList["**/*.coffee"]

desc 'jTtt-web'

define 'jTtt-web' do

  target_dir = _(:target, :generated)
  source_dir = _(:source, :main, :coffee)

  assets.paths << file(target_dir => [coffee_files]) do
    puts "Compiling coffeescript"
    sh "coffee --bare --compile --output #{target_dir} #{source_dir}"
    touch target_dir
  end

  project.group = 'com.danielirvine.jttt'
  project.version = '1'

  compile.with lock_jars
  #compile.with coffee_files
  package(:jar, :id => 'jTtt-web')
  package(:war, :id => 'jTtt-web')
  compile.dependencies.each do |c|
    # exclude signatures to avoid signing errors, and existing war manifests
    package(:jar).merge(c)
      .exclude('META-INF/MANIFEST.MF', 'META-INF/*.RSA', 'META-INF/*.SF','META-INF/*.DSA')
  end
  manifest['Main-Class'] = 'com.danielirvine.jttt.web.WebHandler'
  compile.options.target = '1.8'
  compile.options.source = '1.8'
end

task :compile => coffee_files
